pipeline {
     agent any
     stages {
          stage("Compile") {
               steps {
                    dir('sample2') {
                         sh "chmod +x gradlew"
                         sh "./gradlew compileJava"
                    }
               }
          }
          stage("Unit test") {
               steps {
                    dir('sample2') {
                         sh "./gradlew test"
                    }
               }
          }
          stage("Package") {
               steps {
                    dir('sample2') {
                         sh "./gradlew build"
                    }
               }
          }
          stage("Docker build") {
               steps {
                    dir('sample2') {
                         sh "docker build -t ydima169/calculator ."
                    }
               }
          }
          stage("Docker login") {
               steps {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker-hub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                         sh "docker login --username $USERNAME --password $PASSWORD"
                    }
               }
          }
          stage("Docker push") {
               steps {
                    sh "docker push ydima169/calculator"
               }
          }
          stage("Deploy to staging") {
               steps {
                    sh "docker run -d --rm -p 8765:8080 --name calculator ydima169/calculator"
               }
          }
          stage("Acceptance test") {
               steps {
                    dir('sample2') {
                         sleep 60
                         sh "chmod +x acceptance_test.sh && ./acceptance_test.sh"
                    }
               }
          }
     }
     post {
          always {
               sh "docker stop calculator || true"
          }
     }
}
