pipeline {
     agent any
     stages {
          stage("Compile") {
               steps {
                    dir('sample2') {
                         sh "./gradlew compileJava"
                    }
               }
          }
          stage("Unit test") {
               steps {
                    dir('sample2') {
                         sh "./gradlew test"
                    }
               }
          }
          stage("Package") {
               steps {
                    dir('sample2') {
                         sh "./gradlew build"
                    }
               }
          }
          stage("Docker build") {
               steps {
                    dir('sample2') {
                         sh "docker build -t ydima169/calculator ."
                    }
               }
          }
          stage("Docker login") {
               steps {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker-hub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                         sh "docker login --username $USERNAME --password $PASSWORD"
                    }
               }
          }
          stage("Docker push") {
               steps {
                    sh "docker push ydima169/calculator"
               }
          }
     }
}
